server:
  port: 9192

spring:
  application:
    name: slee-rentHome
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgadmin
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: true
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


logging:
  level:
    com.mteam.sleerenthome.utils.HeaderSizeFilter: DEBUG

security:
  jwt:
    expirationTime: 86400  # 토큰의 유효 기간 (단위: 초)
    secret: 7RVZVt+jGRz9hJTDeqP7XvlLZq3aHW47vUQ955+eLLs=    # JWT 서명을 위한 비밀 키
